/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tech.pegasys.net;

import picocli.CommandLine;
import picocli.CommandLine.Command;
import tech.pegasys.net.cli.BaseFeeCommand;
import tech.pegasys.net.cli.Options;
import tech.pegasys.net.config.FillerMode;
import tech.pegasys.net.core.dagger.DaggerChainFillerComponent;

@Command(
    name = "chain-filler",
    mixinStandardHelpOptions = true,
    version = "chain-filler 1.0",
    description = "Runs the chain-filler tool.")
public class ChainFillerApplication implements Runnable {

  public static void main(final String[] args) {
    final CommandLine commandLine = new CommandLine(new ChainFillerApplication());
    commandLine.registerConverter(FillerMode.class, FillerMode::fromString);
    commandLine.addMixin("chain-filler", Options.getInstance());
    commandLine.addSubcommand(new BaseFeeCommand());
    System.exit(commandLine.execute(args));
  }

  @Override
  public void run() {
    DaggerChainFillerComponent.create().chainFiller().fill();
  }
}
