/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tech.pegasys.net;

import picocli.CommandLine;
import picocli.CommandLine.Command;
import tech.pegasys.net.cli.Options;
import tech.pegasys.net.core.dagger.DaggerTxSenderComponent;

@Command(
    name = "tx-sender",
    mixinStandardHelpOptions = true,
    version = "tx-sender 1.0",
    description = "Runs the tx-sender tool.")
public class Eip1559TxSenderApplication implements Runnable {

  public static void main(final String[] args) {
    final CommandLine commandLine = new CommandLine(new Eip1559TxSenderApplication());
    commandLine.addMixin("tx-sender", Options.getInstance());
    System.exit(commandLine.execute(args));
  }

  @Override
  public void run() {
    DaggerTxSenderComponent.create().txSender().run();
  }
}
